
services:
  - type: web
    name: winball-telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
